/*
 * Licensed to the Apache Software Foundation (ASF) under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for additional information regarding
 * copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License. You may obtain a
 * copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.rsmogura.picoson;

public abstract class JsonSupport<T> {
  //TODO Fill up JavaDoc

  /**
   * Implementation of read - typically generated by annotation processor or
   * class transformer.
   */
  protected abstract T readI(JsonReader in);

  /**
   * Implementation of write - typically generated by annotation processor or
   * class transformer.
   */
  protected abstract void writeI(T src, JsonWriter out);

  public T read(JsonReader in) {
    return readI(in);
  }

  public void write(T src, JsonWriter out) {
    writeI(src, out);
  }
}
